# apiVersion: v1
# kind: Namespace
# metadata:
#   name: finansist
# ---
apiVersion: apps/v1                       
kind: Deployment                          
metadata:                                 
  namespace: finansist                      
  name: finansist              
  labels:                                 
    app: finansist              
spec:                                     
  replicas: 1    
  revisionHistoryLimit: 1
  selector:                               
    matchLabels:                          
      app: finansist                   
  template:                               
    metadata:                 
      labels:                 
        app: finansist
    spec:                     
      containers:             
        - name: finansist      
          # image: "gabrielrodriguesdev/finansist-backend:latest"
          image: "desenvolvedortrdev/finansist-backend:latest"
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: "50Mi"
              cpu: "60m"
            requests:
              memory: "30Mi"
              cpu: "30m"

--- 

apiVersion: v1
kind: Service
metadata:
  namespace: finansist
  name: finansist-service
spec:
  type: ClusterIP
  selector: 
    app: finansist
  ports:
    - name: finansist-service 
      port: 80
      targetPort: 80
      protocol: TCP 



# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   namespace: finansist
#   name: finansist-hpa
# spec:                                                     
#   scaleTargetRef:                                         
#     apiVersion: apps/v1                                   
#     kind: Deployment                                      
#     name: finansist                                        
#   minReplicas: 2                                          
#   maxReplicas: 3
#   targetCPUUtilizationPercentage: 90

---

# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   namespace: finansist
#   name: ingress-finansist
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     cert-manager.io/cluster-issuer: "letsencrypt"
#     nginx.ingress.kubernetes.io/affinity: cookie
#     nginx.ingress.kubernetes.io/affinity-mode: balanced
# spec:
#   rules:
#   - host: "finansist.trdev.com.br"
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           serviceName: finansist-service
#           servicePort: 80
#   tls:
#   - hosts:
#     - "trdev.com.br"
#     - "*.trdev.com.br"
#     secretName: letsencrypt-tls


# apiVersion: networking.k8s.io/v1                                  
# kind: Ingress                                                                 
# metadata:                                                                     
#   namespace: finansist                                                       
#   name: ingress-finansist                                                        
#   annotations:                                                               
#     kubernetes.io/ingress.class: "nginx"                                                               
#     nginx.ingress.kubernetes.io/affinity-mode: balanced                      
# spec:                                                                        
#   rules:                                                                     
#   #- host: "api.finansist.com.br"                                        
#     - http:                                                                    
#         paths:                                                                 
#         - path: /
#           pathType: Prefix                                                     
#           backend:                                                             
#             service: 
#               name: finansist-service
#               port:
#                 number: 80
#   # tls:
#   # - hosts:
#   #   - "finansist.com.br"
#   #   - "*.finansist.com.br"
#   #   secretName: letsencrypt-tls